version: '3.8'

x-system_environment:
  &system_environment
  links:
    - apisonator
    - mailhog
    - memcached
    - mysql
    - redis
  environment:
    - DB_HOST=mysql
    - REDIS_URL=redis://redis/1
    - MEMCACHE_SERVERS=memcached:11211
    - BACKEND_HOST=apisonator:3001
    - BACKEND_REDIS_URL=redis://redis/3
    - SECRET_KEY_BASE=secret
    - THREESCALE_CORE_INTERNAL_API=http://apisonator:3001/internal/
    - CONFIG_INTERNAL_API_USER=system_app
    - CONFIG_INTERNAL_API_PASSWORD=password
    - SMTP_ADDRESS=mailhog
    - SMTP_PORT=1025
    - UNICORN_WORKERS=2
    - FORCE_SSL=false
    - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    - RAILS_MAX_THREADS=25
    - APICAST_REGISTRY_URL=http://${MY_IP}:8090/policies

x-apicast_engironment:
  &apicast_environment
  environment:
    - APICAST_LOG_LEVEL=debug
    - THREESCALE_PORTAL_ENDPOINT=${PORTAL_ENDPOINT}
    - THREESCALE_DEPLOYMENT_ENV=staging
    - BACKEND_ENDPOINT_OVERRIDE=http://apisonator:3001

services:
  system:
    <<: *system_environment
    build:
      context: .
      args:
        CUSTOM_DB: ${DB}
    command: bash -c "rm -f tmp/pids/server.pid && UNICORN_WORKERS=2 bin/rails server -b 0.0.0.0"
    container_name: system-compose
    depends_on:
      - apisonator
      - mailhog
      - memcached
      - redis
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - system-assets:/opt/system/public/assets
      - system-node-modules:/opt/system/node_modules

  sidekiq:
    <<: *system_environment
    image: porta_system
    command: bash -c "rake sidekiq"
    container_name: sidekiq-compose
    depends_on:
      - system

  mysql:
    image: mysql:5.7
    container_name: mysql-compose
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
        test: "mysql --user=root --execute 'SHOW DATABASES;'"
        timeout: 20s
        retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  memcached:
    image: memcached
    container_name: memcached-compose
    ports:
      - "11211:11211"

  apisonator:
    image: quay.io/3scale/apisonator:latest
    container_name: apisonator-compose
    ports:
      - "3001:3001"
    command: "3scale_backend start -p 3001"
    depends_on:
      - redis
    environment:
      - CONFIG_REDIS_PROXY=redis:6379/3
      - CONFIG_QUEUES_MASTER_NAME=redis:6379/3
      - CONFIG_WORKERS_LOG_FILE=/dev/stdout
      - CONFIG_INTERNAL_API_USER=system_app
      - CONFIG_INTERNAL_API_PASSWORD=password
      - RACK_ENV=production

  redis:
    image: redis:alpine
    container_name: redis-compose
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-compose
    ports:
      - "1025:1025"
      - "8025:8025"

  apicast:
    <<: *apicast_environment
    image: registry.redhat.io/3scale-amp2/apicast-gateway-rhel8:3scale2.9
    container_name: my-apicast
    network_mode: host
    dns: ${MY_IP}

  dnsmasq:
    image: strm/dnsmasq
    restart: always
    cap_add: 
      - NET_ADMIN
    container_name: my-dnsmasq
    network_mode: host
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf

volumes:
  mysql-data:
  system-assets:
  system-node-modules:
